### ISSUE TITLE
[FEATURE REQUEST] Game updates

### ISSUE THREAD

**Issue by david-s-morris** [whitewhidow/quest-sideloader-linux#17]
When I see the list of available games I need to know which of these I have already loaded on the quest and of those which in the list are a newer version. If any are newer than the ones installed on my device I want the option to update that game or all games with updates present on my device.

**Comment by whitewhidow** [comment]
step 1. so far ive added this:
when you select an app to sideload, it will first check which version you currently have installed,
will display the old and new version numbers
will tell you if this is a downgrade, upgrade, or simple reinstall of the same version, before prompting to continue or not.

More coming soon to actually complete this feature in more of a way that you have envisioned

**Comment by whitewhidow** [comment]
closing issue since feature is now fully implemented in new cross platform version
https://github.com/whitewhidow/quest-sidenoder
