### ISSUE TITLE
Repeated Unsucessful Mount Attempt (on osx)

### ISSUE THREAD

**Issue by buiyardee** [whitewhidow/quest-sideloader-linux#20]
Like we spoked about on another post, I'm fairly new to all of this. But during this morning update the error disappeared but the program is still struggling to mount. I'm running on a old Macbook Pro perhaps thats the issue. Also is the UI only showing on Linux OS? Let me know if theres anything I can do to help diagnose the issue.

**Comment by whitewhidow** [comment]
the UI should also show on osx,  

are you not seeing anything suspicious in the output, could you please post it here?

if its an option for you,  you can find me at t.me/whitewhidow on telegram, and we can try to debug this one on one with some manual tests and commands, to see exactly where it is failing on your machine

**Comment by whitewhidow** [comment]
Since we managed to get the mount fixed with some one-on-one via telegram,  i will close this particular issue .

isssue was because of an old version of base64 which used capital -D as a parameter, whereas the new version uses small letter -d.

(feel free to open another one for the zenity issue)
