### ISSUE TITLE
mounting throws error,  "failed to mount FUSE fs: exit status 1" (on OSX CATALINA)

### ISSUE THREAD

**Issue by mega-bix** [whitewhidow/quest-sideloader-linux#22]
Hey! I'm that guy who commented on your post on reddit. I have updated, but the error persists. The error message I got is 
ERROR

The mounting process encoutered any issues, please provide me with any errors you may see in the terminal at 
https://github.com/whitewhidow/quest-sideloader-linux/issues
or find me at t.me/whitewhidow_q2_working

And i will gladly assist you!

You can still use 'sideload-gui' to sideload apps you have manually downloaded

[NOTE] Since are on OSX, make sure you have OSXFUSE installed.
run 'brew cask install osxfuse' or go to https://osxfuse.github.io/ (this requires reboot, which is why we dont automate this)
Thanks so much!

**Comment by whitewhidow** [comment]
Hi, please update once again using 
`curl -fsSL https://raw.githubusercontent.com/whitewhidow/quest-sideloader-linux/main/install | /bin/bash -s -- main`

As i have just pushed one osx related mounting fix

to confirm if this is your issue, run `base64 --help`   
if your current setup expects a CAPTIAL -D parameter for Decode, then this last update will fix your mount
if your current setup expects a small latter -d parameter for decode, then we are looking at another issue here.

so please kindly 
1. update everything using the oneliner, OR to test atleast run `brew install base64`
2. manually verify `base64 --help` response and post here (-D vs -d parameter)
3. manually run `whitewhidow /mnt/tmp` which will attempt the mount, without any of the gui related stuff interfering, and please post the terminal output if this aswell, as this will most likely say SOMETHING about the mount failing.

Thank you !

**Comment by carlonzo** [comment]
I believe in the point 3 he meant: `whitewhidow-mount /tmp/mnt` :)

**Comment by whitewhidow** [comment]
CORRECT,   `whitewhidow-mount /tmp/mnt`


edited

**Comment by mega-bix** [comment]
First I want to start by saying I SO MUCH APPRECIATE YOU FOR TAKING TIME OUT OF YOUR DAY TO DO THIS! I have looked into Rclone browsers before but they ended up crashing and I could not get it to work sadly... Anyways, I have updated using the one-liner then restarted, but it did not work, although I got a different response this time. The response was:
ERROR

The mounting process encountered an issues, please provide the terminal output to 
https://github.com/whitewhidow/quest-sideloader-linux/issues

And i will gladly assist you!

[NOTE] Since are on OSX, you may simply need to reboot first, and re-run this script, as we may have installed a dependency (OSXFUSE) which requires a reboot !


You can still use 'sideload-gui' to sideload apps you have manually downloaded

Next I tried "whitewhidow-mount /tmp/mnt"
which gave an output of:

<img width="561" alt="Screen Shot 2020-10-30 at 7 10 14 PM" src="https://user-images.githubusercontent.com/46059707/97769615-b3223e00-1ae9-11eb-9d67-5effc80865e2.png">

Then I tried "brew install base64"
which gave an output of:


<img width="554" alt="Screen Shot 2020-10-30 at 7 55 20 PM" src="https://user-images.githubusercontent.com/46059707/97769626-d8af4780-1ae9-11eb-86dc-fac9ff5bceb2.png">

When I tried the "base64 --help" I got: 
<img width="494" alt="Screen Shot 2020-10-30 at 8 35 10 PM" src="https://user-images.githubusercontent.com/46059707/97770323-6a6d8380-1aef-11eb-8ef8-b3134dc89e36.png">

**Comment by whitewhidow** [comment]
the base64 issue has been resolved already, so that part can be completely ignored now.

i see the screenshot saying : `fusermount: command not found`, which i think should be provided by this OSXFUSE package...

(any chance you know if my installer installed osxfuse, or did my installer say osxfuse was already installed?)

Is it at all an option for you to contact me on telegram ? at https://t.me/whitewhidow
(that way we can run trough some commands one by one, and actually figure out what is actually going wrong .
specifically)

**Comment by mega-bix** [comment]
Sure! I joined Telegram but I'm not sure if the installer installed osxfuse.

**Comment by whitewhidow** [comment]
i dont see you on tele,   send me a pm there please,   username is "whitewhidow", you can find me in the list of users in the channel  (or just yell for me in the channel, ill definitely see it)

**Comment by mega-bix** [comment]
Thanks to whitewhidow's wonderful support, he/she managed to fix it up to the point of me being able to access the games on webgui, but was unfortunately unable to mount the drive.

**Comment by mega-bix** [comment]
IMPORTANT! Thanks to whitewhidow and the new OSXFUSE update(pre-release) the issue has been resolved. If you are experiencing the same issue as me, try to update to the new OSXFUSE update.

**Comment by carlonzo** [comment]
Did you have to manually compile the sources ?
