### ISSUE TITLE
Issue mounting osxfuse on macOS 11 (Big-Sur BETA)

### ISSUE THREAD

**Issue by carlonzo** [whitewhidow/quest-sideloader-linux#23]
receiving this when running quest-sideloader on macos 11.

`2020/10/30 13:55:51 Fatal error: failed to mount FUSE fs: exit status 1`

osx fuse should be supporting macos 11, but maybe better wait for https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.0 to be available on brew?

**Comment by whitewhidow** [comment]
> osx fuse should be supporting macos 11, but maybe better wait for https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.0 to be available on brew?

aha,  yep,  hopefully they add it soon, in which case this might resolve itself at that point, if not, i guess i have some work to do ;)

**Comment by whitewhidow** [comment]
have confirmed on another mac user which had the same issue, installing the osxfuse4 prerelease fixed it .

@carlonzo can you verify by chance?

**Comment by carlonzo** [comment]
Sure thing

**Comment by whitewhidow** [comment]
closing issue since development moved to 
https://github.com/whitewhidow/quest-sidenoder
