### ISSUE TITLE
failed 8\8 mount 

### ISSUE THREAD

**Issue by madmax-X** [whitewhidow/quest-sideloader-linux#47]
mounting of drive fails, worked fine a few weeks ago
updated to latest stable release -no change

your telegram doesnt show up when searching for @whitewhidow, only @whitewhidow21

terminal output:

[INFO ] Starting mount process
[OK   ] Mount-config detected successfully: WHITEWHIDOW_QUEST:
nohup: appending output to 'nohup.out'
[INFO ] Checking if drive is mounted (attempt 1/8)
ls: reading directory '/tmp/mnt': Input/output error
[INFO ] Checking if drive is mounted (attempt 2/8)
ls: reading directory '/tmp/mnt': Input/output error
[INFO ] Checking if drive is mounted (attempt 3/8)
ls: reading directory '/tmp/mnt': Input/output error
[INFO ] Checking if drive is mounted (attempt 4/8)
ls: reading directory '/tmp/mnt': Input/output error
[INFO ] Checking if drive is mounted (attempt 5/8)
ls: reading directory '/tmp/mnt': Input/output error
[INFO ] Checking if drive is mounted (attempt 6/8)
ls: reading directory '/tmp/mnt': Input/output error
[INFO ] Checking if drive is mounted (attempt 7/8)
ls: reading directory '/tmp/mnt': Input/output error
[INFO ] Checking if drive is mounted (attempt 8/8)

tail of nohub.out:

~$ tail nohup.out 
Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}
<7>DEBUG : /: Attr: 
<7>DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
<7>DEBUG : /: ReadDirAll: 
<7>DEBUG : : Dir.ReadDirAll error: couldn't list directory: Get "https://www.googleapis.com/drive/v3/files?alt=json&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks%29%2CnextPageToken%2CincompleteSearch&includeItemsFromAllDrives=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%271_pqwvo9UrLAYiRee-M5VAKixGjL5-phR%27+in+parents%29&supportsAllDrives=true": oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}
<7>DEBUG : /: >ReadDirAll: item=-1, err=couldn't list directory: Get "https://www.googleapis.com/drive/v3/files?alt=json&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks%29%2CnextPageToken%2CincompleteSearch&includeItemsFromAllDrives=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%271_pqwvo9UrLAYiRee-M5VAKixGjL5-phR%27+in+parents%29&supportsAllDrives=true": oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}
<6>INFO  : Signal received: interrupt
<6>INFO  : Exiting...

**Comment by whitewhidow** [comment]
read the first 2 lines of the readme
